### ISSUE TITLE
Deprecate repo?

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/go-rpc#14]
This started as a discussion here: https://github.com/tendermint/go-rpc/pull/12#discussion_r107434667 but after further investigation, I wonder why we have this at all.

@ebuchman I did a search through all tendermint repos that I have checked out, and looked for all imports of go-rpc. It is currently used in `tendermint/rpc/core` to create a server, and `tendermint/rpc/client` to consume this service. In `basecoin` and `lil-voterin` to consume this rpc (which can now be upgraded to use `tendermint/rpc/client` as a higher-level interface). And in `tendermint/node/node.go:startRPC` to start up the server.

As far as I can tell, the requirements are that we can implement the tendermint/rpc/client.Client interface over http (get and post), as well as subscribing to events over websockets. And a server that provides easy bindings to functions of [this format](https://github.com/tendermint/tendermint/blob/master/rpc/core/abci.go#L10).

Whatever glue code goes between calling the client and calling the server is largely irrelavent, as long as it can easily be called over HTTP (and for bucky also as get parameters in the browser).

One could build a much simpler binding using the stdlib net/http package along with gorilla/websockets. Rather than this level of abstraction and casting, which makes everything quite fragile, you could even auto-generate bindings using go-swagger or a similar technique.

Given that:
  * @melekes spent many days trying to make minor adjustments to the API using go-rpc
  * this repo is only used as the public API
  * we want to be able to easily design the public API, as aesthetics and ease of use are essential for integration with 3rd party developers. 
  * there is simpler, standard tooling available

I propose that:
  * We design the public API as we want it to look as a consumer, without worrying about backwards compatibility
  * And we build/use the best tooling we can to achieve this goal.

This becomes a bit more urgent, as my task of switching from go-wire JSON encoding to go-data JSON encoding, in preparation of merging the two repos, requires that I make modifications to the rpc interface, as this is the principal location the json encoding is exposed to consumers.

**Comment by zramsay** [comment]
this has happened
