### ISSUE TITLE
better error in client if method does not exist

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-rpc#2]
The difficulty in debugging https://github.com/eris-ltd/eris-db/issues/253 stems from the client trying to unmarshal the main page (the list of endpoints, which is returned if the method does not exist) into a return type, which it's not

**Comment by zramsay** [comment]
Issue moved to [tendermint/tendermint #612](https://github.com/tendermint/tendermint/issues/612) via [**ZenHub**](https://www.zenhub.com/)
