### ISSUE TITLE
methods shouldn't require all params

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-rpc#7]
Should be possible to call endpoints without providing all params!

eg this doesn't work:

```
curl -s 'localhost:46657/abci_query?data="abcd"'
```

I have to do 

```
curl -s 'localhost:46657/abci_query?data="abcd"&path=""&prove=false'
```

**Comment by mappum** [comment]
Would we want to set default values for all the optional args, or would there be a default for each type? ("" for strings, false for bools?)

**Comment by ebuchman** [comment]
I figured default for the type, but might be good if we could also override that with a preset default!
